### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by manuxi** [jolichter/visWidgetUpdater#1]
Thank you for your script.

I just tested it but faced the error "File ring_0_doorbell_xxx_HDSnapshot.jpg&t=1734378228686 not found: {}".

After changing the ampersand (&) to questionmark (?) on two places in your code it seems to work.

So it should be

````
newImg.onload = () => {
        logMessage(`Bild für Widget "${widgetId}" erfolgreich geladen.`, 'info');
        img.src = `${url}?t=${new Date().getTime()}`; // Tausche das Bild nahtlos aus
    };

    newImg.onerror = () => {
        logMessage(`Bild für Widget "${widgetId}" konnte nicht geladen werden.`, 'error');
    };

    newImg.src = `${url}?t=${new Date().getTime()}`; // Löst das Laden aus
````

**Comment by jolichter** [comment]
Hi manuxi, thank you for your feedback! The original code always appended an ampersand (&) to the URL, which only works correctly if the URL already contains query parameters (?). I have optimized the code to handle this properly now.

Could you please test it and let me know if it works for you (V 24.12.002)?

**Comment by manuxi** [comment]
Ah, I see. This wasn't the case here.

**Comment by manuxi** [comment]
Since I saw the "missing image icon" from time to time I made some changes to the script. Now the image is properly preloaded on my side:
````
    const { url } = widgetData[widgetId];
    const newImg = new Image();
    const timestamp = new Date().getTime(); 
    newImg.src = `${url}?t=${timestamp}`;

    newImg.onload = () => {
        logMessage(`Bild für Widget "${widgetId}" erfolgreich geladen.`, 'info');
        img.src = newImage.src
    };
````

**Comment by jolichter** [comment]
Thank you for your improvements, I've optimized the preloading, timestamp and error handling (V 24.12.003).

**Comment by jolichter** [comment]
done with V 24.12.004
